### PR TITLE
Work for issues #8 & #9

### PR DESCRIPTION
**Pull request by garymoon**
Hi Matt,

Please let me know if anything isn't to your liking.

Cheers,
Gary.

### CODE REVIEW

**Comment by MattMcFarland** [comment]
Looks great, can you add yourself to package.json and update the version?
For semver this would be a new feature so the second number would
increment.  Then I'll pull in the changes and update npm

On Tue, Jan 26, 2016 at 2:34 PM, Gary Moon notifications@github.com wrote:

> Hi Matt,
> 
> Please let me know if anything isn't to your liking.
> 
> Cheers,
> 
> ## Gary.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/MattMcFarland/SUq/pull/10
> Commit Summary
> - Fix unchecked reference in microdata cleaner (issue #9)
> - Add "Gary Moon" to contributors
> - add overview of request-option-passing to readme
> - add recipe for request-option-passing
> - typo fix
> 
> File Changes
> - _M_ README.md
>   https://github.com/MattMcFarland/SUq/pull/10/files#diff-0 (13)
> - _M_ lib/cleanMicrodata.js
>   https://github.com/MattMcFarland/SUq/pull/10/files#diff-1 (8)
> - _A_ recipes/request-options.js
>   https://github.com/MattMcFarland/SUq/pull/10/files#diff-2 (7)
> 
> Patch Links:
> - https://github.com/MattMcFarland/SUq/pull/10.patch
> - https://github.com/MattMcFarland/SUq/pull/10.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/SUq/pull/10.

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by garymoon** [comment]
Hi Matt,

All done. Thanks again!

Gary.

**Comment by MattMcFarland** [comment]
Thanks!! I've updated the package on npm :)

**Comment by garymoon** [comment]
Thanks Matt, all working perfectly!

**Pull request merged**
